apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: app-name
      type: string
      default: counter-service
    - name: build-image
      type: string
      default: counter-service:latest
    - name: namespace
      type: string
      default: ci-cd-project
  workspaces:
    - name: source
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source
    
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/Shahzar-Ali/ci-cd-final-project.git
        - name: revision
          value: main
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - cleanup

    - name: flake8-linting
      taskRef:
        name: flake8-lint
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - git-clone
    
    - name: nose-tests
      taskRef:
        name: nose
      params:
        - name: args
          value: "-v --with-spec --spec-color --with-coverage --cover-package=service"
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - flake8-linting
    
    - name: buildah-build
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - nose-tests
      securityContext:
        runAsUser: 0
        privileged: true
    
    - name: deploy-app
      taskRef:
        name: deploy
      params:
        - name: app-name
          value: $(params.app-name)
        - name: build-image
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - buildah-build
