# git-clone task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: source
  params:
    - name: url
      description: Git repository URL
      type: string
  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        git clone $(params.url) .

---
# flake8-lint task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip
        pip install flake8
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

---
# buildah task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
    - name: source
  params:
    - name: image
      description: Image name to build
      type: string
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        buildah bud -t $(params.image) .

---
# deploy task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  steps:
    - name: oc-deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -e
        oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
